--------------------------------------------------------
--  File created - Friday-June-19-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_CONTRACT
--------------------------------------------------------

  CREATE TABLE "SCOTT"."USER_CONTRACT" 
   (	"USER_CONTRACT_ID" NUMBER(10,0), 
	"CREATE_DATE" TIMESTAMP (6), 
	"COMPANY_NAME" VARCHAR2(255 CHAR), 
	"DURATION" VARCHAR2(255 CHAR), 
	"EXP" VARCHAR2(255 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UR_MASTER_ID" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_DETAILS
--------------------------------------------------------

  CREATE TABLE "SCOTT"."USER_DETAILS" 
   (	"USERID" NUMBER(10,0), 
	"CREATE_DATE" TIMESTAMP (6), 
	"DOB" TIMESTAMP (6), 
	"DOJ" TIMESTAMP (6), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"FNAME" VARCHAR2(255 CHAR), 
	"IS_ACTIVE" NUMBER(1,0), 
	"LNAME" VARCHAR2(255 CHAR), 
	"MOBILE_NO" NUMBER(19,0), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UR_MASTER_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_MASTER
--------------------------------------------------------

  CREATE TABLE "SCOTT"."USER_MASTER" 
   (	"USERM_ID" NUMBER(10,0), 
	"CREATE_DATE" TIMESTAMP (6), 
	"IS_ACTIVE" NUMBER(1,0), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"USER_NAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_ADDRES
--------------------------------------------------------

  CREATE TABLE "SCOTT"."USER_ADDRES" 
   (	"USER_ADDRS_ID" NUMBER(10,0), 
	"CREATE_DATE" TIMESTAMP (6), 
	"STREET_NAME" VARCHAR2(255 CHAR), 
	"CITY_NAME" VARCHAR2(255 CHAR), 
	"HOUSE_NO" VARCHAR2(255 CHAR), 
	"PIN_CODE" NUMBER(10,0), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"USER_MS_ADD_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_EDUCATION
--------------------------------------------------------

  CREATE TABLE "SCOTT"."USER_EDUCATION" 
   (	"UREDUID" NUMBER(10,0), 
	"CREATE_DATE" TIMESTAMP (6), 
	"USER_CLG_CITY_NAM" VARCHAR2(255 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"USER_BRANCH_NAME" VARCHAR2(255 CHAR), 
	"USER_CLG_NAME" VARCHAR2(255 CHAR), 
	"USER_SC_CITY_NAME" VARCHAR2(255 CHAR), 
	"USER_SC_NAME" VARCHAR2(255 CHAR), 
	"USER_MS_EDU_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.USER_CONTRACT
SET DEFINE OFF;
REM INSERTING into SCOTT.USER_DETAILS
SET DEFINE OFF;
Insert into SCOTT.USER_DETAILS (USERID,CREATE_DATE,DOB,DOJ,EMAIL,FNAME,IS_ACTIVE,LNAME,MOBILE_NO,UPDATE_DATE,UR_MASTER_ID) values (7,to_timestamp('18-06-20 11:39:47.595000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),to_timestamp('10-10-96 03:30:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),to_timestamp('18-06-18 03:30:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),'rahul@gmail.com','rahul Hj',1,'sharma ji',0,to_timestamp('19-06-20 01:10:13.096000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),359);
REM INSERTING into SCOTT.USER_MASTER
SET DEFINE OFF;
Insert into SCOTT.USER_MASTER (USERM_ID,CREATE_DATE,IS_ACTIVE,PASSWORD,UPDATE_DATE,USER_NAME) values (1,to_timestamp('18-06-20 05:15:02.141000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),null,'sharma',to_timestamp('18-06-20 05:15:02.141000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'Amit');
Insert into SCOTT.USER_MASTER (USERM_ID,CREATE_DATE,IS_ACTIVE,PASSWORD,UPDATE_DATE,USER_NAME) values (52,to_timestamp('18-06-20 05:31:19.661000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),null,'sharma',to_timestamp('18-06-20 05:31:19.661000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'rahul');
Insert into SCOTT.USER_MASTER (USERM_ID,CREATE_DATE,IS_ACTIVE,PASSWORD,UPDATE_DATE,USER_NAME) values (102,to_timestamp('18-06-20 05:52:51.031000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),1,'sharma',to_timestamp('18-06-20 05:52:51.031000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'rahul');
Insert into SCOTT.USER_MASTER (USERM_ID,CREATE_DATE,IS_ACTIVE,PASSWORD,UPDATE_DATE,USER_NAME) values (103,to_timestamp('18-06-20 06:02:37.683000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),1,'sharma',to_timestamp('18-06-20 06:02:37.683000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'rahul');
Insert into SCOTT.USER_MASTER (USERM_ID,CREATE_DATE,IS_ACTIVE,PASSWORD,UPDATE_DATE,USER_NAME) values (152,to_timestamp('18-06-20 06:07:55.082000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),1,'sharma',to_timestamp('18-06-20 06:07:55.082000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'rahul');
Insert into SCOTT.USER_MASTER (USERM_ID,CREATE_DATE,IS_ACTIVE,PASSWORD,UPDATE_DATE,USER_NAME) values (302,to_timestamp('18-06-20 06:42:52.135000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),1,'sharma',to_timestamp('18-06-20 06:42:52.135000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'rahul');
Insert into SCOTT.USER_MASTER (USERM_ID,CREATE_DATE,IS_ACTIVE,PASSWORD,UPDATE_DATE,USER_NAME) values (358,to_timestamp('18-06-20 07:06:57.638000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),1,'sharma',to_timestamp('18-06-20 07:06:57.638000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'rahul');
Insert into SCOTT.USER_MASTER (USERM_ID,CREATE_DATE,IS_ACTIVE,PASSWORD,UPDATE_DATE,USER_NAME) values (359,to_timestamp('18-06-20 07:08:06.723000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),1,'sharma',to_timestamp('18-06-20 07:08:06.723000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'rahul');
REM INSERTING into SCOTT.USER_ADDRES
SET DEFINE OFF;
Insert into SCOTT.USER_ADDRES (USER_ADDRS_ID,CREATE_DATE,STREET_NAME,CITY_NAME,HOUSE_NO,PIN_CODE,UPDATE_DATE,USER_MS_ADD_ID) values (152,to_timestamp('18-06-20 06:42:52.247000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'45ZRoad','bhopal','hh',452456,to_timestamp('18-06-20 06:42:52.247000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),302);
Insert into SCOTT.USER_ADDRES (USER_ADDRS_ID,CREATE_DATE,STREET_NAME,CITY_NAME,HOUSE_NO,PIN_CODE,UPDATE_DATE,USER_MS_ADD_ID) values (208,to_timestamp('18-06-20 07:06:57.677000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'45ZRoad','bhopal','hh',452456,to_timestamp('18-06-20 07:06:57.677000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),358);
Insert into SCOTT.USER_ADDRES (USER_ADDRS_ID,CREATE_DATE,STREET_NAME,CITY_NAME,HOUSE_NO,PIN_CODE,UPDATE_DATE,USER_MS_ADD_ID) values (209,to_timestamp('18-06-20 07:08:06.727000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'45ZRoad','bhopal','hh',452456,to_timestamp('18-06-20 07:08:06.727000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),359);
REM INSERTING into SCOTT.USER_EDUCATION
SET DEFINE OFF;
Insert into SCOTT.USER_EDUCATION (UREDUID,CREATE_DATE,USER_CLG_CITY_NAM,UPDATE_DATE,USER_BRANCH_NAME,USER_CLG_NAME,USER_SC_CITY_NAME,USER_SC_NAME,USER_MS_EDU_ID) values (258,to_timestamp('18-06-20 07:08:06.730000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'indore',to_timestamp('18-06-20 07:08:06.730000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),'cse','vit','sanawad','ssvm',359);
--------------------------------------------------------
--  DDL for Index SYS_C0013819
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0013819" ON "SCOTT"."USER_CONTRACT" ("USER_CONTRACT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013827
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0013827" ON "SCOTT"."USER_DETAILS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013833
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0013833" ON "SCOTT"."USER_MASTER" ("USERM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013816
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0013816" ON "SCOTT"."USER_ADDRES" ("USER_ADDRS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013829
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0013829" ON "SCOTT"."USER_EDUCATION" ("UREDUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USER_CONTRACT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."USER_CONTRACT" MODIFY ("USER_CONTRACT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."USER_CONTRACT" MODIFY ("UR_MASTER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."USER_CONTRACT" ADD PRIMARY KEY ("USER_CONTRACT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_DETAILS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."USER_DETAILS" MODIFY ("USERID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."USER_DETAILS" MODIFY ("DOB" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."USER_DETAILS" MODIFY ("DOJ" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."USER_DETAILS" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."USER_DETAILS" MODIFY ("FNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."USER_DETAILS" MODIFY ("LNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."USER_DETAILS" MODIFY ("UR_MASTER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."USER_DETAILS" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_MASTER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."USER_MASTER" MODIFY ("USERM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."USER_MASTER" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."USER_MASTER" MODIFY ("USER_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."USER_MASTER" ADD PRIMARY KEY ("USERM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_ADDRES
--------------------------------------------------------

  ALTER TABLE "SCOTT"."USER_ADDRES" MODIFY ("USER_ADDRS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."USER_ADDRES" ADD CHECK (pin_code>=111111 AND pin_code<=999999) ENABLE;
 
  ALTER TABLE "SCOTT"."USER_ADDRES" ADD PRIMARY KEY ("USER_ADDRS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_EDUCATION
--------------------------------------------------------

  ALTER TABLE "SCOTT"."USER_EDUCATION" MODIFY ("UREDUID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."USER_EDUCATION" ADD PRIMARY KEY ("UREDUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_CONTRACT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."USER_CONTRACT" ADD CONSTRAINT "FKKUO5LVQDK5TT4R0VK80HJ9GVC" FOREIGN KEY ("UR_MASTER_ID")
	  REFERENCES "SCOTT"."USER_MASTER" ("USERM_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_DETAILS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."USER_DETAILS" ADD CONSTRAINT "FKE48J7RIR22HC7CY6AFWM6LN3Q" FOREIGN KEY ("UR_MASTER_ID")
	  REFERENCES "SCOTT"."USER_MASTER" ("USERM_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_ADDRES
--------------------------------------------------------

  ALTER TABLE "SCOTT"."USER_ADDRES" ADD CONSTRAINT "FKS2RH80R36GPJ5AV85VMFCQKC8" FOREIGN KEY ("USER_MS_ADD_ID")
	  REFERENCES "SCOTT"."USER_MASTER" ("USERM_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_EDUCATION
--------------------------------------------------------

  ALTER TABLE "SCOTT"."USER_EDUCATION" ADD CONSTRAINT "FKBF5GD0JMAPKSKU2862DX6S3BI" FOREIGN KEY ("USER_MS_EDU_ID")
	  REFERENCES "SCOTT"."USER_MASTER" ("USERM_ID") ENABLE;
